# Generated by Django 5.0.4 on 2024-08-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='title1',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='team',
            name='title2',
        ),
    ]
