# Generated by Django 5.0.4 on 2024-08-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_title1_team_title_remove_team_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team2',
            name='title',
        ),
    ]
