# Generated by Django 5.0.4 on 2024-09-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_team2_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='name_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='name_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='name_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='by',
            name='name',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='by',
            name='name_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='by',
            name='name_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='by',
            name='name_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='by',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='by',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='by',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='our',
            name='name_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='our',
            name='name_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='our',
            name='name_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='our',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='our',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='our',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title1_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title1_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title1_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title2_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title2_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title2_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title3_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title3_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title3_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title4_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title4_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title4_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title5_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title5_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title5_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title6_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title6_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title6_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title7_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title7_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='title7_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='e_mail_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='e_mail_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='e_mail_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='ism_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='ism_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='ism_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='pro_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='pro_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='pro_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sevice',
            name='name_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='sevice',
            name='name_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='sevice',
            name='name_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='sevice',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sevice',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sevice',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='title_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='title_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='title_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='team2',
            name='name_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='team2',
            name='name_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='team2',
            name='name_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='team2',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team2',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='team2',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='nomi',
            field=models.CharField(default=1, max_length=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='nomi_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='nomi_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='nomi_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='name_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='name_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='name_uz',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='title_en',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='title_ru',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='title_uz',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
